export type Language = 'en' | 'bn' | 'hi';

export const translations = {
  en: {
    // Navigation
    home: 'Home',
    benefits: 'Discover Benefits',
    report: 'Report Issue',
    map: 'Civic Map',
    dashboard: 'My Activity',
    community: 'Community',
    about: 'About',
    findBenefitsCTA: 'Find My Benefits',
    reportIssueCTA: 'Report Civic Issue',
    exploreMapCTA: 'Explore Civic Map',
    citizenPortal: 'Citizen Portal',
    authorityPortal: 'Officer Portal',
    notifications: 'Notifications',

    // Hero Section
    heroBadge: 'AI-POWERED CIVIC WELFARE & GRIEVANCE PLATFORM',
    heroTitle1: 'Discover the benefits',
    heroTitle2: 'you deserve.',
    heroTitle3: 'Make every civic issue',
    heroTitle4: 'count.',
    heroDescription: 'Nagrik Setu helps citizens discover welfare schemes they may be missing, report community problems, track government action, and verify whether those problems were actually solved.',
    
    // Feature Cards
    notAnotherPortal: 'Not another complaint portal.',
    feature1Title: 'Benefit Gap AI',
    feature1Desc: 'Discover opportunities citizens may be missing instead of waiting for them to search.',
    feature2Title: 'Civic Cluster Intelligence',
    feature2Desc: 'Transform duplicate complaints into community-level evidence.',
    feature3Title: 'Citizen-Verified Resolution',
    feature3Desc: 'Government action becomes transparent—and resolution is confirmed by the people affected.',
    feature4Title: 'Civic Health Intelligence',
    feature4Desc: 'Turn grievance data into neighbourhood-level insights for better public decision-making.',

    // Stats
    citizensAssisted: 'Citizens Assisted',
    potentialBenefits: 'Potential Benefits Identified',
    issuesReported: 'Civic Issues Reported',
    verifiedResolution: 'Citizen-Verified Resolution',
    demoData: 'Demo Mode Simulation',

    // Footer
    footerDesc: 'Nagrik Setu connects communities with public welfare support and transforms municipal reporting into citizen-verified progress.',
    footerNote: 'Nagrik Setu is a civic technology platform. All services are provided on an as-is basis.',

    // Welfare journey steps
    howItWorks: 'How Nagrik Setu Works',
    welfareJourney: 'Welfare Journey',
    civicJourney: 'Civic Journey',
    wStep1: 'Tell us about yourself',
    wStep2: 'AI checks eligibility',
    wStep3: 'Benefits discovered',
    wStep4: 'Document readiness',
    wStep5: 'Application guidance',
    cStep1: 'Report issue',
    cStep2: 'AI understands it',
    cStep3: 'Similar reports clustered',
    cStep4: 'Authority assigned',
    cStep5: 'Progress tracked',
    cStep6: 'Citizen verifies resolution',

    // Auth Strings
    loginTitle: 'Welcome back',
    loginSubtitle: 'Sign in to your Jansetu account to continue',
    registerTitle: 'Create an account',
    registerSubtitle: 'Join Nagrik Setu to connect with your community',
    emailLabel: 'Email Address',
    passwordLabel: 'Password',
    nameLabel: 'Full Name',
    phoneLabel: 'Phone Number (Optional)',
    roleLabel: 'Account Type',
    citizenRole: 'Citizen',
    officerRole: 'Municipal Officer',
    officerCodeLabel: 'Officer Verification Code',
    officerCodePlaceholder: 'Enter official verification code',
    signInBtn: 'Sign In',
    signUpBtn: 'Create Account',
    loggingIn: 'Signing in...',
    registering: 'Creating account...',
    noAccount: "Don't have an account?",
    hasAccount: 'Already have an account?',
    forgotPassword: 'Forgot password?',
    emailUnconfirmedTitle: 'Email Verification Required',
    emailUnconfirmedDesc: 'Please check your email inbox to verify your address before logging in.',
    resendEmailBtn: 'Resend Verification Email',
    emailResentSuccess: 'Verification email sent! Check your inbox.',
    resending: 'Sending email...',
    registrationSuccessTitle: 'Check Your Email',
    registrationSuccessDesc: 'We sent a verification link to your email address. Please click the link to activate your account before logging in.',

    // Report Page
    reportPageTitle: 'Report a Civic Issue',
    reportPageSubtitle: 'Describe the problem in your voice or text. AI will classify, geotag, and route it to the right municipal team.',
    describeProblem: 'Describe the problem',
    describePlaceholder: 'e.g. Broken streetlight near Ward 12 market creating safety issues at night...',
    voiceInputBtn: 'Voice Input',
    photoUpload: 'Upload Photo',
    autoGps: 'Camera & GPS Geotagged Location',
    aiClassifying: 'AI analyzing report details...',
    aiPreviewTitle: 'AI Classification Preview',
    categoryLabel: 'Category',
    priorityLabel: 'Priority',
    departmentLabel: 'Assigned Department',
    clusterAlertTitle: 'Existing Cluster Nearby',
    clusterAlertDesc: 'other citizens have reported similar issues in this area.',
    anonymousOption: 'Report anonymously (your name will not be shown publicly)',
    submitGrievanceBtn: 'Submit Grievance',
    submittingGrievance: 'Submitting grievance...',

    // Dashboard
    myActivityTitle: 'My Activity & Submissions',
    officerDashboardTitle: 'Authority Action Portal',
    filterAll: 'All Issues',
    filterPending: 'Pending Action',
    filterResolved: 'Resolved',
    filterDisputed: 'Disputed',
    confirmResolutionTitle: 'Citizen Resolution Verification',
    verifyResolutionPrompt: 'Has this issue been satisfactorily fixed by municipal workers?',
    yesSatisfied: 'Yes, Issue Resolved',
    noNotSatisfied: 'No, Re-open & Dispute',

    // Common
    loading: 'Loading...',
    error: 'An error occurred',
    success: 'Success',
    back: 'Back',
    cancel: 'Cancel',
    save: 'Save',
    submit: 'Submit'
  },

  bn: {
    // Navigation
    home: 'হোম',
    benefits: 'ভাতা ও প্রকল্প',
    report: 'অভিযোগ জানান',
    map: 'নাগরিক মানচিত্র',
    dashboard: 'আমার কর্মকাণ্ড',
    community: 'সম্প্রদায়',
    about: 'আমাদের সম্পর্কে',
    findBenefitsCTA: 'আমার প্রকল্প খুঁজুন',
    reportIssueCTA: 'সমস্যা রিপোর্ট করুন',
    exploreMapCTA: 'মানচিত্র দেখুন',
    citizenPortal: 'নাগরিক পোর্টাল',
    authorityPortal: 'প্রশাসন পোর্টাল',
    notifications: 'বিজ্ঞপ্তি',

    // Hero Section
    heroBadge: 'এআই-চালিত নাগরিক কল্যাণ ও অভিযোগ প্রতিকার প্ল্যাটফর্ম',
    heroTitle1: 'আপনার যোগ্য সরকারি সুবিধা',
    heroTitle2: 'খুঁজে নিন।',
    heroTitle3: 'প্রতিটি নাগরিক সমস্যার',
    heroTitle4: 'সমাধান করুন।',
    heroDescription: 'নাগরিক সেতু নাগরিকদের এমন সব সরকারি ভাতা বা প্রকল্প খুঁজে পেতে সাহায্য করে যা তারা হয়তো পাননি, পাশাপাশি স্থানীয় সমস্যা নথিভুক্ত করা, সরকারি পদক্ষেপ ট্র্যাক করা এবং অভিযোগটি সত্যিই সমাধান হয়েছে কিনা তা যাচাই করার সুবিধা দেয়।',
    
    // Feature Cards
    notAnotherPortal: 'এটি কেবল আরেকটি অভিযোগ পোর্টাল নয়।',
    feature1Title: 'বেনিফিট গ্যাপ এআই',
    feature1Desc: 'নাগরিকরা নিজে খোঁজার অপেক্ষায় না থেকে তাদের সম্ভাব্য ভাতাগুলি স্বয়ংক্রিয়ভাবে আবিষ্কার করুন।',
    feature2Title: 'নাগরিক ক্লাস্টার ইন্টেলিজেন্স',
    feature2Desc: 'একাধিক একই অভিযোগকে একটি একক সমষ্টিগত কমিউনিটি প্রমাণে রূপান্তরিত করুন।',
    feature3Title: 'নাগরিক-যাচাইকৃত সমাধান',
    feature3Desc: 'সরকারি পদক্ষেপ হয় সম্পূর্ণ স্বচ্ছ—এবং সমাধানটি সরাসরি ভুক্তভোগী নাগরিক দ্বারা নিশ্চিত করা হয়।',
    feature4Title: 'নাগরিক স্বাস্থ্য সূচক',
    feature4Desc: 'উন্নত প্রশাসনিক সিদ্ধান্তের জন্য অভিযোগের তথ্যকে পাড়া-ভিত্তিক বিশ্লেষণে রূপান্তর করুন।',

    // Stats
    citizensAssisted: 'সহায়তা প্রাপ্ত নাগরিক',
    potentialBenefits: 'চিহ্নিত সম্ভাব্য অনুদান',
    issuesReported: 'রিপোর্টকৃত নাগরিক সমস্যা',
    verifiedResolution: 'নাগরিক-যাচাইকৃত সমাধান',
    demoData: 'ডেমো মোড সিমুলেশন',

    // Footer
    footerDesc: 'নাগরিক সেতু সম্প্রদায়গুলিকে জনকল্যাণমূলক সহায়তার সাথে যুক্ত করে এবং পুরসভার অভিযোগ ব্যবস্থাপনাকে নাগরিক-যাচাইকৃত অগ্রগতির স্তরে উন্নীত করে।',
    footerNote: 'নাগরিক সেতু একটি নাগরিক প্রযুক্তি প্ল্যাটফর্ম। সমস্ত পরিষেবা যথারীতি প্রদান করা হয়।',

    // Welfare journey steps
    howItWorks: 'নাগরিক সেতু যেভাবে কাজ করে',
    welfareJourney: 'কল্যাণমূলক যাত্রা',
    civicJourney: 'নাগরিক যাত্রা',
    wStep1: 'নিজের সম্পর্কে বলুন',
    wStep2: 'এআই যোগ্যতা পরীক্ষা করবে',
    wStep3: 'প্রকল্প আবিষ্কৃত হবে',
    wStep4: 'নথিপত্র প্রস্তুতি',
    wStep5: 'আবেদন নির্দেশিকা',
    cStep1: 'সমস্যা রিপোর্ট করুন',
    cStep2: 'এআই সমস্যা বুঝবে',
    cStep3: 'সমজাতীয় সমস্যা ক্লাস্টার হবে',
    cStep4: 'দপ্তর বরাদ্দ হবে',
    cStep5: 'অগ্রগতি ট্র্যাক হবে',
    cStep6: 'নাগরিক সমাধান যাচাই করবে',

    // Auth Strings
    loginTitle: 'স্বাগতম',
    loginSubtitle: 'চালিয়ে যেতে আপনার জনসেতু অ্যাকাউন্টে সাইন ইন করুন',
    registerTitle: 'অ্যাকাউন্ট তৈরি করুন',
    registerSubtitle: 'জনসেতুতে যোগ দিন এবং আপনার সম্প্রদায়ের সাথে যুক্ত হন',
    emailLabel: 'ইমেল ঠিকানা',
    passwordLabel: 'পাসওয়ার্ড',
    nameLabel: 'সম্পূর্ণ নাম',
    phoneLabel: 'ফোন নম্বর (ঐচ্ছিক)',
    roleLabel: 'অ্যাকাউন্টের ধরণ',
    citizenRole: 'নাগরিক',
    officerRole: 'পুরসভা কর্মকর্তা',
    officerCodeLabel: 'অফিসার যাচাইকরণ কোড',
    officerCodePlaceholder: 'অফিসিয়াল যাচাইকরণ কোড লিখুন',
    signInBtn: 'সাইন ইন করুন',
    signUpBtn: 'অ্যাকাউন্ট তৈরি করুন',
    loggingIn: 'সাইন ইন হচ্ছে...',
    registering: 'অ্যাকাউন্ট তৈরি হচ্ছে...',
    noAccount: 'অ্যাকাউন্ট নেই?',
    hasAccount: 'ইতিমধ্যে অ্যাকাউন্ট আছে?',
    forgotPassword: 'পাসওয়ার্ড ভুলে গেছেন?',
    emailUnconfirmedTitle: 'ইমেল যাচাইকরণ প্রয়োজন',
    emailUnconfirmedDesc: 'লগ ইন করার আগে অনুগ্রহ করে আপনার ইমেল ইনবক্স চেক করে ইমেল যাচাই করুন।',
    resendEmailBtn: 'যাচাইকরণ ইমেল পুনরায় পাঠান',
    emailResentSuccess: 'যাচাইকরণ ইমেল পাঠানো হয়েছে! ইনবক্স দেখুন।',
    resending: 'ইমেল পাঠানো হচ্ছে...',
    registrationSuccessTitle: 'আপনার ইমেল চেক করুন',
    registrationSuccessDesc: 'আমরা আপনার ইমেল ঠিকানায় একটি যাচাইকরণ লিঙ্ক পাঠিয়েছি। লগ ইন করার আগে লিঙ্কটিতে ক্লিক করে আপনার অ্যাকাউন্টটি সক্রিয় করুন।',

    // Report Page
    reportPageTitle: 'নাগরিক সমস্যা রিপোর্ট করুন',
    reportPageSubtitle: 'কণ্ঠে বা লেখায় সমস্যাটি জানান। এআই এটি শ্রেণীবদ্ধ করে সঠিক পুরসভা দলের কাছে পাঠাবে।',
    describeProblem: 'সমস্যার বিবরণ দিন',
    describePlaceholder: 'যেমন: ১২ নম্বর ওয়ার্ডের বাজারের কাছে স্ট্রিটলাইট নষ্ট থাকায় রাতে সুরক্ষার সমস্যা হচ্ছে...',
    voiceInputBtn: 'ভয়েস ইনপুট',
    photoUpload: 'ছবি আপলোড করুন',
    autoGps: 'ক্যামেরা এবং জিপিএস অবস্থান',
    aiClassifying: 'এআই সমস্যা বিশ্লেষণ করছে...',
    aiPreviewTitle: 'এআই শ্রেণীবিভাগ পূর্বরূপ',
    categoryLabel: 'বিভাগ',
    priorityLabel: 'অগ্রাধিকার',
    departmentLabel: 'বরাদ্দকৃত দপ্তর',
    clusterAlertTitle: 'নিকটবর্তী সমজাতীয় ক্লাস্টার',
    clusterAlertDesc: 'জন নাগরিক এই এলাকায় একই ধরনের সমস্যা রিপোর্ট করেছেন।',
    anonymousOption: 'বেনামে রিপোর্ট করুন (আপনার নাম প্রকাশ করা হবে না)',
    submitGrievanceBtn: 'অভিযোগ জমা দিন',
    submittingGrievance: 'অভিযোগ জমা হচ্ছে...',

    // Dashboard
    myActivityTitle: 'আমার কর্মকাণ্ড এবং অভিযোগসমূহ',
    officerDashboardTitle: 'কার্যাবলী ও প্রশাসনিক পোর্টাল',
    filterAll: 'সমস্ত সমস্যা',
    filterPending: 'প্রক্রিয়াধীন',
    filterResolved: 'সমাধানকৃত',
    filterDisputed: 'বিতর্কিত',
    confirmResolutionTitle: 'নাগরিক সমাধান যাচাইকরণ',
    verifyResolutionPrompt: 'পুরসভার কর্মীরা কি এই সমস্যাটি সন্তোষজনকভাবে সমাধান করেছেন?',
    yesSatisfied: 'হ্যাঁ, সমাধান সফল',
    noNotSatisfied: 'না, পুনরায় খুলুন ও আপত্তি জানান',

    // Common
    loading: 'লোড হচ্ছে...',
    error: 'একটি ত্রুটি ঘটেছে',
    success: 'সফল',
    back: 'ফিরে যান',
    cancel: 'বাতিল',
    save: 'সংরক্ষণ',
    submit: 'জমা দিন'
  },

  hi: {
    // Navigation
    home: 'होम',
    benefits: 'योजनाएं खोजें',
    report: 'समस्या दर्ज करें',
    map: 'नागरिक मानचित्र',
    dashboard: 'मेरी गतिविधियां',
    community: 'कम्युनिटी',
    about: 'हमारे बारे में',
    findBenefitsCTA: 'मेरी योजनाएं खोजें',
    reportIssueCTA: 'समस्या दर्ज करें',
    exploreMapCTA: 'मानचित्र देखें',
    citizenPortal: 'नागरिक पोर्टल',
    authorityPortal: 'अधिकारी पोर्टल',
    notifications: 'अधिसूचनाएं',

    // Hero Section
    heroBadge: 'एआई-संचालित नागरिक कल्याण और शिकायत निवारण मंच',
    heroTitle1: 'सरकारी लाभों को',
    heroTitle2: 'प्राप्त करें।',
    heroTitle3: 'हर नागरिक समस्या को',
    heroTitle4: 'हल करें।',
    heroDescription: 'नागरिक सेतु नागरिकों को उन कल्याणकारी योजनाओं को खोजने में मदद करता है जिनसे वे वंचित हैं, साथ ही स्थानीय समस्याओं को दर्ज करने, सरकारी कार्रवाई को ट्रैक करने और समस्याओं के वास्तविक समाधान को सत्यापित करने की सुविधा देता है।',
    
    // Feature Cards
    notAnotherPortal: 'यह कोई साधारण शिकायत पोर्टल नहीं है।',
    feature1Title: 'बेनिफिट गैप एआई',
    feature1Desc: 'नागरिकों द्वारा खोजने का इंतजार किए बिना उन्हें मिलने वाले लाभों का स्वचालित रूप से पता लगाएं।',
    feature2Title: 'नागरिक क्लस्टर इंटेलिजेंस',
    feature2Desc: 'एक ही स्थान की कई शिकायतों को एक समुदाय-स्तरीय समस्या और साक्ष्य में बदलें।',
    feature3Title: 'नागरिक-सत्यापित समाधान',
    feature3Desc: 'सरकारी कार्रवाई को पारदर्शी बनाएं—और समाधान की पुष्टि स्वयं प्रभावित लोगों द्वारा की जाती है।',
    feature4Title: 'नागरिक स्वास्थ्य इंटेलिजेंस',
    feature4Desc: 'बेहतर प्रशासनिक निर्णयों के लिए शिकायत डेटा को वार्ड-स्तरीय विश्लेषण में बदलें।',

    // Stats
    citizensAssisted: 'सहायता प्राप्त नागरिक',
    potentialBenefits: 'संभावित लाभ राशि',
    issuesReported: 'दर्ज नागरिक समस्याएं',
    verifiedResolution: 'नागरिक-सत्यापित समाधान',
    demoData: 'डेमो मोड सिमुलेशन',

    // Footer
    footerDesc: 'नागरिक सेतु समुदायों को सार्वजनिक कल्याणकारी योजनाओं से जोड़ता है और नगर निगम की शिकायतों को नागरिक-सत्यापित प्रगति में बदलता है।',
    footerNote: 'नागरिक सेतु एक नागरिक प्रौद्योगिकी मंच है। सभी सेवाएं यथावत प्रदान की जाती हैं।',

    // Welfare journey steps
    howItWorks: 'नागरिक सेतु कैसे काम करता है',
    welfareJourney: 'कल्याणकारी यात्रा',
    civicJourney: 'नागरिक यात्रा',
    wStep1: 'अपने बारे में बताएं',
    wStep2: 'एआई योग्यता जांचेगा',
    wStep3: 'योजनाएं सामने आएंगी',
    wStep4: 'दस्तावेज़ की तैयारी',
    wStep5: 'आवेदन मार्गदर्शन',
    cStep1: 'समस्या दर्ज करें',
    cStep2: 'एआई समस्या समझेगा',
    cStep3: 'समान शिकायतें एकत्र होंगी',
    cStep4: 'अधिकारी नियुक्त होगा',
    cStep5: 'प्रगति ट्रैक होगी',
    cStep6: 'नागरिक समाधान सत्यापित करेगा',

    // Auth Strings
    loginTitle: 'स्वागत है',
    loginSubtitle: 'जारी रखने के लिए अपने जनसेतु खाते में साइन इन करें',
    registerTitle: 'खाता बनाएं',
    registerSubtitle: 'नागरिक सेतु में शामिल हों और अपने समुदाय से जुड़ें',
    emailLabel: 'ईमेल पता',
    passwordLabel: 'पासवर्ड',
    nameLabel: 'पूरा नाम',
    phoneLabel: 'फोन नंबर (वैकल्पिक)',
    roleLabel: 'खाते का प्रकार',
    citizenRole: 'नागरिक',
    officerRole: 'नगर निगम अधिकारी',
    officerCodeLabel: 'अधिकारी सत्यापन कोड',
    officerCodePlaceholder: 'आधिकारिक सत्यापन कोड दर्ज करें',
    signInBtn: 'साइन इन करें',
    signUpBtn: 'खाता बनाएं',
    loggingIn: 'साइन इन हो रहा है...',
    registering: 'खाता बन रहा है...',
    noAccount: 'खाता नहीं है?',
    hasAccount: 'पहले से खाता है?',
    forgotPassword: 'पासवर्ड भूल गए?',
    emailUnconfirmedTitle: 'ईमेल सत्यापन आवश्यक',
    emailUnconfirmedDesc: 'लॉग इन करने से पहले कृपया अपना ईमेल इनबॉक्स जांचकर ईमेल सत्यापित करें।',
    resendEmailBtn: 'पुनः सत्यापन ईमेल भेजें',
    emailResentSuccess: 'सत्यापन ईमेल भेज दिया गया है! इनबॉक्स जांचें।',
    resending: 'ईमेल भेजा जा रहा है...',
    registrationSuccessTitle: 'अपना ईमेल जांचें',
    registrationSuccessDesc: 'हमने आपके ईमेल पते पर एक सत्यापन लिंक भेजा है। लॉग इन करने से पहले अपने खाते को सक्रिय करने के लिए लिंक पर क्लिक करें।',

    // Report Page
    reportPageTitle: 'नागरिक समस्या दर्ज करें',
    reportPageSubtitle: 'बोलकर या लिखकर समस्या बताएं। एआई इसे वर्गीकृत करके सही अधिकारी टीम को भेजेगा।',
    describeProblem: 'समस्या का विवरण दें',
    describePlaceholder: 'जैसे: वार्ड 12 बाजार के पास स्ट्रीटलाइट खराब होने से रात में सुरक्षा की समस्या है...',
    voiceInputBtn: 'वॉइस इनपुट',
    photoUpload: 'फोटो अपलोड करें',
    autoGps: 'कैमरा और जीपीएस लोकेशन',
    aiClassifying: 'एआई समस्या का विश्लेषण कर रहा है...',
    aiPreviewTitle: 'एआई वर्गीकरण पूर्वावलोकन',
    categoryLabel: 'श्रेणी',
    priorityLabel: 'प्राथमिकता',
    departmentLabel: 'आवंटित विभाग',
    clusterAlertTitle: 'आस-पास मौजूदा क्लस्टर',
    clusterAlertDesc: 'अन्य नागरिकों ने इस क्षेत्र में ऐसी ही समस्याएं दर्ज की हैं।',
    anonymousOption: 'गुमनाम रूप से दर्ज करें (आपका नाम सार्वजनिक रूप से नहीं दिखाया जाएगा)',
    submitGrievanceBtn: 'शिकायत दर्ज करें',
    submittingGrievance: 'शिकायत दर्ज हो रही है...',

    // Dashboard
    myActivityTitle: 'मेरी गतिविधियां और शिकायतें',
    officerDashboardTitle: 'अधिकारी कार्रवाई पोर्टल',
    filterAll: 'सभी समस्याएं',
    filterPending: 'लंबित कार्रवाई',
    filterResolved: 'समाधान हो चुका',
    filterDisputed: 'विवादित',
    confirmResolutionTitle: 'नागरिक समाधान सत्यापन',
    verifyResolutionPrompt: 'क्या नगर निगम कर्मचारियों ने इस समस्या का समाधान संतोषजनक ढंग से किया है?',
    yesSatisfied: 'हां, समाधान हो गया',
    noNotSatisfied: 'नहीं, पुन: खोलें और आपत्ति दर्ज करें',

    // Common
    loading: 'लोड हो रहा है...',
    error: 'एक त्रुटि हुई',
    success: 'सफलता',
    back: 'वापस',
    cancel: 'रद्द करें',
    save: 'सहेजें',
    submit: 'जमा करें'
  }
};

export const localization = translations;